<?php
    $arrayLang_no = array(
        "CATEGORIE_3" => "Muskel- og skjelettsmerter og generell helse",
        "P18_TITLE" => "Smertelokalisering",
        "P18_LABEL" => "Kryss av for de områdene der du for tiden har smerter.",
        "P20_TITLE" => "Livskvalitet",
        "P20_1_LABEL" => "Under hver overskrift ber vi deg krysse av den ENE boksen som best beskriver helsen dinI DAG.",
        "P20_1_QUESTION_1" => "GANGE",
        "P20_1_QUESTION_2" => "PERSONLIG STELL",
        "P20_1_QUESTION_3" => "VANLIGE GJØREMÅL (f.eks. arbeid, studier, husarbeid, familie-eller fritidsaktiviteter)",
        "P20_1_QUESTION_4" => "SMERTER/UBEHAG",
        "P20_1_QUESTION_5" => "ANGST/DEPRESJON",
        "P20_1_ANSWER_1_1" => "Jeg har ingen problemer medå gå omkring.",
        "P20_1_ANSWER_1_2" => "Jeg har litt problemer med å gå omkring.",
        "P20_1_ANSWER_1_3" => "Jeg har middels store problemer med å gå omkring.",
        "P20_1_ANSWER_1_4" => "Jeg har store problemer med å gå omkring.",
        "P20_1_ANSWER_1_5" => "Jeg er ute av stand til å gå omkring.",
        "P20_1_ANSWER_2_1" => "Jeg har ingen problemer med å vaske meg eller kle meg.",
        "P20_1_ANSWER_2_2" => "Jeg har litt problemer med å vaske meg eller kle meg.",
        "P20_1_ANSWER_2_3" => "Jeg har middels store problemer med å vaske meg eller kle meg.",
        "P20_1_ANSWER_2_4" => "Jeg har store problemer med å vaske meg eller kle meg.",
        "P20_1_ANSWER_2_5" => "Jeg er ute av stand til å vaske meg eller kle meg.",
        "P20_1_ANSWER_3_1" => "Jeg har ingen problemer med å utføre mine vanlige gjøremål.",
        "P20_1_ANSWER_3_2" => "Jeg har litt problemer med å utføre mine vanlige gjøremål.",
        "P20_1_ANSWER_3_3" => "Jeg har middels store problemer med å utføre mine vanlige gjøremål.",
        "P20_1_ANSWER_3_4" => "Jeg har store problemer med å utføre mine vanlige gjøremål.",
        "P20_1_ANSWER_3_5" => "Jeg er ute av stand til å utføre mine vanlige gjøremål.",
        "P20_1_ANSWER_4_1" => "Jeg har verken smerter eller ubehag.",
        "P20_1_ANSWER_4_2" => "Jeg har litt smerter eller ubehag.",
        "P20_1_ANSWER_4_3" => "Jeg har middels sterke smerter eller ubehag.",
        "P20_1_ANSWER_4_4" => "Jeg har sterke smerter eller ubehag.",
        "P20_1_ANSWER_4_5" => "Jeg har svært sterke smerter eller ubehag.",
        "P20_1_ANSWER_5_1" => "Jeg er verken engstelig eller deprimert.",
        "P20_1_ANSWER_5_2" => "Jeg er litt engstelig eller deprimert.",
        "P20_1_ANSWER_5_3" => "Jeg er middels engstelig eller deprimert.",
        "P20_1_ANSWER_5_4" => "Jeg er svært engstelig eller deprimert.",
        "P20_1_ANSWER_5_5" => "Jeg er ekstremt engstelig eller deprimert.",
        "P20_2_INSTRUCTION_1" => "Vi vil gjerne vite hvor god eller dårlig helsen din er I <strong>DAG</strong>.",
        "P20_2_INSTRUCTION_2" => "Denne skalaen er nummerert fra <strong>0</strong> til <strong>100</strong>.",
        "P20_2_INSTRUCTION_3" => "<strong>100</strong> betyr den <u>beste</u> helsen du kan tenke deg.<br/><strong>0</strong> betyr den <u>dårligste</u> helsen du kan tenke deg.",
        "P20_2_INSTRUCTION_4" => "Nå kan du klikke på skalaen for å indikere hvordan helsen din er <strong>I DAG</strong>, eller du kan skrive inn nummeret i boksen nedenfor.",
        "P20_2_SCALE_HEADER" => "Den beste helsen<br/>du kan tenke deg",
        "P20_2_SCALE_FOOTER" => "Den dårligste<br/>helsen du kan<br/>tenke deg",
        "P20_2_RESULT" => "HELSEN DIN I DAG =",
        "P20_2_CONFIRM" => "Er du sikker på at din helse tilstand i dag er 0?",
        "P20_2_ALERT_NUMBER" => "Fyll inn et positivt heltall mellom 0 og 100 i boksen nedenfor."
    );
?>